
# H2
spring:
  datasource:
    url: jdbc:h2:mem:statements
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  application:
    name: StatementProcessor