# H2
spring:
  datasource:
    url: jdbc:h2:mem:statements
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  application:
    name: StatementProcessor
  batch:
    job:
      enabled: false
file:
  csv:
    input: "/input/records.csv"
    output: "errorsCsv.json"
  xml:
    input: "/input/records.xml"
    output: "errorsXml.json"
app:
  clear-db: true